create table if not exists public.ota_releases (
  id bigint generated by default as identity primary key,
  channel text not null default 'production' check (channel in ('production', 'beta')),
  platform text not null default 'all' check (platform in ('all', 'android', 'ios')),
  bundle_version text not null,
  file_path text not null,
  checksum text,
  mandatory boolean not null default false,
  enabled boolean not null default true,
  rollout_percent integer not null default 100 check (rollout_percent between 1 and 100),
  native_min_version text,
  native_max_version text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (channel, platform, bundle_version)
);

create index if not exists idx_ota_releases_lookup
  on public.ota_releases (channel, platform, enabled, created_at desc);

create or replace function public.set_updated_at_ota_releases()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_ota_releases on public.ota_releases;
create trigger trg_set_updated_at_ota_releases
before update on public.ota_releases
for each row
execute function public.set_updated_at_ota_releases();

alter table public.ota_releases enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'ota-bundles',
  'ota-bundles',
  false,
  52428800,
  array['application/zip', 'application/octet-stream']
)
on conflict (id) do nothing;
